# NAMA : Fransiskus Andre
# NIM  : 20091065
# POSTTEST 7

## Import Library


In [17]:
import tensorflow as tf

## buat tensor random

In [18]:
random_tensor = tf.random.normal([5,5])
random_tensor
a = random_tensor


In [19]:
a.shape

TensorShape([5, 5])

## buat tensor untuk bilangan prima

In [20]:
prime = [37,43,23,2,7],[3,5,97,131,149],[181,191,193,197,199],[101,103,107,109,113],[127,137,139,149,151]
tensor_prime = tf.convert_to_tensor(prime, dtype = tf.float32)
b = tensor_prime

In [21]:
a.shape

TensorShape([5, 5])

In [22]:
random_tensor.shape

TensorShape([5, 5])

## Operasi ada tensor

### Penjumlahan

In [23]:
tf.add(a,b)

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[ 38.757236 ,  41.9793   ,  22.455496 ,   3.7326145,   8.016006 ],
       [  2.9325325,   6.237413 ,  98.1977   , 131.09172  , 151.94662  ],
       [182.26846  , 192.26698  , 193.49539  , 199.56339  , 199.8975   ],
       [100.10746  , 101.851204 , 106.71179  , 107.44209  , 112.94217  ],
       [126.937874 , 134.68034  , 140.07144  , 148.3921   , 151.48727  ]],
      dtype=float32)>

### Perpangkatan

In [24]:
tf.pow(a,b)

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[ 1.14474304e+09, -2.41329169e+00, -8.47251670e-07,
         3.00195312e+00,  1.11757052e+00],
       [-3.07102484e-04,  2.90116906e+00,  3.97788880e+07,
         0.00000000e+00,             inf],
       [ 4.93487372e+18,  4.25969628e+19,  0.00000000e+00,
                    inf,  4.51011728e-10],
       [-1.03117873e-05, -1.60355450e+06,  0.00000000e+00,
        -9.70722330e+20,  0.00000000e+00],
       [ 0.00000000e+00,            -inf,  1.46321875e+04,
        -6.16318741e-33,  0.00000000e+00]], dtype=float32)>

### Perkalian

In [25]:
tf.multiply(a,b)

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[ 6.50177078e+01, -4.38900795e+01, -1.25235767e+01,
         3.46522903e+00,  7.11204433e+00],
       [-2.02402413e-01,  6.18706417e+00,  1.16176605e+02,
         1.20144444e+01,  4.39047546e+02],
       [ 2.29591782e+02,  2.41994217e+02,  9.56099319e+01,
         5.04987305e+02,  1.78603180e+02],
       [-9.01464081e+01, -1.18326157e+02, -3.08380661e+01,
        -1.69812103e+02, -6.53461075e+00],
       [-7.89040947e+00, -3.17793427e+02,  1.48929611e+02,
        -9.05754395e+01,  7.35776443e+01]], dtype=float32)>

### Pembagian

In [26]:
tf.divide(a,b)

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[ 4.7492851e-02, -2.3737198e-02, -2.3674058e-02,  8.6630726e-01,
         1.4514376e-01],
       [-2.2489158e-02,  2.4748257e-01,  1.2347391e-02,  7.0010166e-04,
         1.9776026e-02],
       [ 7.0080822e-03,  6.6334317e-03,  2.5667783e-03,  1.3012119e-02,
         4.5100674e-03],
       [-8.8370172e-03, -1.1153375e-02, -2.6935160e-03, -1.4292746e-02,
        -5.1175588e-04],
       [-4.8920634e-04, -1.6931824e-02,  7.7081728e-03, -4.0797913e-03,
         3.2269482e-03]], dtype=float32)>

### logaritma

In [27]:
tf.math.log(a,b)

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[ 0.5637418 ,         nan,         nan,  0.54963154,  0.0158796 ],
       [        nan,  0.21302274,  0.18040048, -2.3890877 ,  1.0806614 ],
       [ 0.23780583,  0.2366404 , -0.7024135 ,  0.9413296 , -0.10813833],
       [        nan,         nan,         nan,         nan,         nan],
       [        nan,         nan,  0.06899985,         nan, -0.7189385 ]],
      dtype=float32)>

### Min Max

In [28]:
min_column = tf.argmin(a,axis = 0)
max_column = tf.argmax(a,axis = 0)
max_row = tf.argmax(a,axis = 1)
min_row = tf.argmin(a,axis = 0)
print("nilai minimal kolom : ", min_column)
print("nilai maximal kolom :", max_column)
print("nilai minimal baris : ", min_row)
print("nilai maximal baris :", max_row)

nilai minimal kolom :  tf.Tensor([3 4 0 3 3], shape=(5,), dtype=int64)
nilai maximal kolom : tf.Tensor([0 2 1 2 1], shape=(5,), dtype=int64)
nilai minimal baris :  tf.Tensor([3 4 0 3 3], shape=(5,), dtype=int64)
nilai maximal baris : tf.Tensor([0 4 3 4 2], shape=(5,), dtype=int64)


### Penggabungan

In [29]:
tf_gabung = tf.concat([a,b],axis = 0)
tf_gabung

<tf.Tensor: shape=(10, 5), dtype=float32, numpy=
array([[ 1.7572354e+00, -1.0206995e+00, -5.4450333e-01,  1.7326145e+00,
         1.0160064e+00],
       [-6.7467473e-02,  1.2374128e+00,  1.1976969e+00,  9.1713317e-02,
         2.9466279e+00],
       [ 1.2684629e+00,  1.2669854e+00,  4.9538824e-01,  2.5633874e+00,
         8.9750344e-01],
       [-8.9253873e-01, -1.1487976e+00, -2.8820622e-01, -1.5579093e+00,
        -5.7828415e-02],
       [-6.2129207e-02, -2.3196599e+00,  1.0714360e+00, -6.0788888e-01,
         4.8726919e-01],
       [ 3.7000000e+01,  4.3000000e+01,  2.3000000e+01,  2.0000000e+00,
         7.0000000e+00],
       [ 3.0000000e+00,  5.0000000e+00,  9.7000000e+01,  1.3100000e+02,
         1.4900000e+02],
       [ 1.8100000e+02,  1.9100000e+02,  1.9300000e+02,  1.9700000e+02,
         1.9900000e+02],
       [ 1.0100000e+02,  1.0300000e+02,  1.0700000e+02,  1.0900000e+02,
         1.1300000e+02],
       [ 1.2700000e+02,  1.3700000e+02,  1.3900000e+02,  1.4900000e+02,
      

### Sorting

In [30]:
tf_sort = tf.argsort(tf_gabung,direction="DESCENDING")
tf_sort

<tf.Tensor: shape=(10, 5), dtype=int32, numpy=
array([[0, 3, 4, 2, 1],
       [4, 1, 2, 3, 0],
       [3, 0, 1, 4, 2],
       [4, 2, 0, 1, 3],
       [2, 4, 0, 3, 1],
       [1, 0, 2, 4, 3],
       [4, 3, 2, 1, 0],
       [4, 3, 2, 1, 0],
       [4, 3, 2, 1, 0],
       [4, 3, 2, 1, 0]], dtype=int32)>